from pathlib import Path
import sys
ROOT = Path(__file__).resolve().parents[1]
read=lambda p:(ROOT/p).read_text()
provider=read('components/guided-workflow-provider.tsx')
controller=read('components/guided-controller.tsx')
component=read('components/resolution-handoff.tsx')
helper=read('lib/evidence/resolution-handoff.ts')
ui=read('lib/ui/resolution-handoff.ts')
service=read('lib/services/applicationops-service.ts')
schema=read('prisma/schema.prisma')
integration=read('tests/integration/applicationops.db.test.ts')
page=read('app/page.tsx')
checks=[]
def check(name, ok, detail): checks.append((name,bool(ok),detail))
for path in ['components/resolution-handoff.tsx','lib/evidence/resolution-handoff.ts','lib/ui/resolution-handoff.ts','tests/unit/resolution-handoff.test.ts','tests/unit/resolution-handoff-ui.test.ts','prisma/migrations/20260903120000_pass13_resolution_handoff/migration.sql']:
    check('artifact::'+path,(ROOT/path).exists(),path+' exists')
check('provider_resolve_call','/resolve`' in provider and 'case 5:' in provider,'Step 5 calls guarded resolve endpoint.')
check('controller_resolve_action','RESOLVE INCIDENT' in controller,'Controller exposes explicit resolution action.')
check('controller_not_disabled_after_validation','rollbackExecuting}' in controller and 'validationComplete}' not in controller,'Validated state is actionable rather than disabled.')
check('page_handoff','<ResolutionHandoff />' in page,'Resolution section uses dedicated PASS 13 component.')
check('no_preview_of_unpersisted_summary','view.technicalSummary' not in component and 'view.businessSummary' not in component,'Browser does not preview unpersisted closure copy before resolution.')
check('server_derives_summaries','deriveResolutionHandoff' in service,'Server derives closure summaries from persisted evidence.')
check('atomic_resolution','prisma.$transaction' in service and 'RESOLUTION_HANDOFF_CREATED' in service and 'INCIDENT_RESOLVED' in service,'Summary persistence and closure audits occur in transaction.')
check('persisted_fields','closureTechnicalSummary' in schema and 'closureBusinessSummary' in schema,'Prisma persists both closure summaries.')
check('migration_fields','closureTechnicalSummary' in read('prisma/migrations/20260903120000_pass13_resolution_handoff/migration.sql'),'PASS 13 migration adds closure fields.')
check('validation_guard','allRequiredValidationPassed' in helper and 'VALIDATION_PASSED' in helper,'Handoff requires 4/4 persisted validation plus audit evidence.')
check('recovery_guard','recoveryEvidencePassCount(evidence) !== 4' in helper,'Handoff fails closed when post-validation recovery evidence drifts.')
check('synthetic_boundary','synthetic data only' in helper.lower(),'Business handoff retains synthetic-data boundary.')
check('ui_modes',all(x in ui for x in ['"LOCKED"','"READY"','"RESOLVED"','"INCONSISTENT"']),'UI closure state is fail-closed.')
check('resolved_requires_summaries','hasSummaries && summariesMatch && resolvedAudit && handoffAudit' in ui,'RESOLVED display requires evidence-matching summaries and both closure audits.')
check('integration_sequence','RESOLUTION_HANDOFF_CREATED' in integration,'DB golden path expects handoff audit before resolution.')
check('integration_persistence','closureTechnicalSummary' in integration and 'closureBusinessSummary' in integration,'DB tests assert persisted summaries.')
check('integration_drift_negative','RESOLUTION_EVIDENCE_INCOMPLETE' in integration,'DB source covers post-validation evidence drift.')
check('pass14_freeze',not (ROOT/'components/presentation-mode.tsx').exists() and 'Presentation Mode' not in provider,'No PASS 14 presentation implementation introduced.')
failed=[c for c in checks if not c[1]]
for name,ok,detail in checks: print(('PASS' if ok else 'FAIL'),name,'-',detail)
print(f'\nchecks={len(checks)} passed={len(checks)-len(failed)} failed={len(failed)}')
if failed: sys.exit(1)
print('PASS13_RESOLUTION_HANDOFF_GATE_PASS')
